### ISSUE TITLE
Cars stuck

### ISSUE THREAD

**Issue by bitwombat** [klemola/liikennematto#35]
The live demo, with four cars, had two of them stuck toggling between 0 and -20 m/s^2 acceleration (speed of 0 m/s)

It's the two pointed at below.

![image](https://user-images.githubusercontent.com/3937658/136553254-37a73364-4c3e-4c73-8324-dc7fbf7740a0.png)
![image](https://user-images.githubusercontent.com/3937658/136553286-47895f49-f774-48f8-a9d4-35b0c4b99ceb.png)

**Comment by klemola** [comment]
Thanks for the bug report! I'll take a look.
