### ISSUE TITLE
Missing asset car_white_1.png

### ISSUE THREAD

**Issue by hanneskaeufler** [klemola/liikennematto#44]
hey @klemola,

awesome project, got me really excited to poke around and play with it.
I think the debug menu is missing an asset **car_white_1.png**:

<img width="957" alt="Bildschirmfoto 2022-05-03 um 20 12 54" src="https://user-images.githubusercontent.com/68024/166516440-a3bac0fc-6f6e-48d1-8b08-28e01eaea6d7.png">

Probably just forgot to check it in or sth. Rock on!

**Comment by klemola** [comment]
I've finally fixed the missing icon, along with other UI tweaks. Thanks for reporting the issue, and I hope you'll enjoy the latest version!
